version: '3.8'

services:
  artemia-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV:-development}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'